project:
  type: book

book:
  title: "BEMA"
  author: "Jonathan Salo"
  date: "9/27/2025"
  chapters:
    - index.qmd
    - part: "BEMA"
      chapters:
      - israel.qmd
      - prophets.qmd
      - roman_history.qmd
      - acts.qmd
      - references.qmd
    - part: "Life Church"
      chapters:
       - Foxes.qmd

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand
  pdf:
    documentclass: scrreprt
