project:
  type: book

book:
  title: "BEMA"
  author: "Jonathan Salo"
  date: "9/27/2025"
  chapters:
    - index.qmd
    - part: "BEMA"
      chapters:
      - concepts..qmd
      - israel.qmd
      - prophets.qmd
      - roman_history.qmd
      - acts.qmd
      - hebrews.qmd
      - references.qmd
    - part: "Life Church"
      chapters:
      - premarital_coaching.qmd
      - drew_foxes_questions.qmd
      - Foxes.qmd
    - part: "Jon Tyson"
      - jon_tyson.qmd

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand
  pdf:
    documentclass: scrreprt
